create table "Products"
(
    "Id"               integer generated by default as identity
        constraint "PK_Products"
            primary key,
    "Name"             text                  not null,
    "Url"              text                  not null,
    "StockState"       text                  not null,
    "Image"            text,
    "CurrentPrice"     double precision,
    "Rate"             double precision,
    "Description"      text,
    "TechnicalDetails" text[],
    "CreatedDate"      timestamp             not null,
    "UpdatedDate"      timestamp             not null,
    "isTracking"       boolean default false not null,
    "isFavorite"       boolean default false not null
);

alter table "Products"
    owner to postgres;

create table "TrackedProducts"
(
    "Id"              integer generated by default as identity
        constraint "PK_TrackedProducts"
            primary key,
    "ProductId"       integer                                                           not null,
    "CurrentPrice"    double precision                                                  not null,
    "TargetPrice"     double precision                                                  not null,
    "Interval"        integer                                                           not null,
    "PriceHistory"    text[]                                                            not null,
    "CreatedDate"     timestamp                                                         not null,
    "UpdatedDate"     timestamp                                                         not null,
    "NextRunTime"     timestamp        default '-infinity'::timestamp without time zone not null,
    "MailSendingDate" timestamp        default '-infinity'::timestamp without time zone not null,
    "PriceChange"     double precision default 0.0                                      not null
);

alter table "TrackedProducts"
    owner to postgres;

create table "Emails"
(
    "Id"          integer generated by default as identity
        constraint "PK_Emails"
            primary key,
    "Name"        text      not null,
    "MailAddress" text      not null,
    "CreatedDate" timestamp not null,
    "UpdatedDate" timestamp not null
);

alter table "Emails"
    owner to postgres;

create table "ExportCSV"
(
    id     serial not null
        constraint exportcsv_pk
            primary key,
    "Job"  text   not null,
    email  text   not null,
    name   text   not null,
    gender text
);

alter table "ExportCSV"
    owner to postgres;

create unique index exportcsv_id_uindex
    on "ExportCSV" (id);
